### ISSUE TITLE
Add associations => delete functionality in Models

### ISSUE THREAD

**Issue by iriscoopers** [navase/boatconnection#15]
see http://guides.rubyonrails.org/association_basics.html
![screenshot from 2016-02-10 12 19 23](https://cloud.githubusercontent.com/assets/16886513/12945862/9ae85944-cff0-11e5-93f9-2a9ac11bec45.png)

**Comment by iriscoopers** [comment]
research how this works => do we need to change destroy associations in each model when we add a User model? Or should we use "user has_many boats through" etc..

**Comment by ChielHackman** [comment]
I think that we need to add dependent: :destroy in the user model.
In the user model we associate the boat, the offer and the reservation so it will destroy that data ass wel.

**Comment by iriscoopers** [comment]
Delete boat => delete offerings, reservations
Delete offering => delete reservation
Delete reservation => nothing associated, BUT offering should show empty slot again (this is for later when we figure out how to work with the available / blocked dates)

**Comment by navase** [comment]
http://guides.rubyonrails.org/association_basics.html#the-has-many-through-association

**Comment by ChielHackman** [comment]
pushed it in master!
